# Generated by Django 3.1.7 on 2021-03-19 14:01

from django.db import migrations


def remove_maas_operators(apps, schema_editor):
    """Allows adding the one-to-one field without any problems.

    There should be only development data if any.
    """
    MaasOperator = apps.get_model("maas", "MaasOperator")
    MaasOperator.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("maas", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(remove_maas_operators, migrations.RunPython.noop),
    ]
