# Generated by Django 3.1.7 on 2021-03-19 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("maas", "0002_remove_existing_maas_operators"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="maasoperator",
            name="api_token",
        ),
        migrations.AddField(
            model_name="maasoperator",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="maas_operator",
                to="auth.user",
                verbose_name="user",
            ),
            preserve_default=False,
        ),
    ]
