# Generated by Django 3.1.7 on 2021-03-29 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("maas", "0003_add_user_to_maas_operator"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketingSystem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="name")),
            ],
            options={
                "verbose_name": "ticketing system",
                "verbose_name_plural": "ticketing systems",
            },
        ),
        migrations.AlterModelOptions(
            name="transportserviceprovider",
            options={
                "default_related_name": "transport_service_providers",
                "verbose_name": "transport service provider",
                "verbose_name_plural": "transport service provider",
            },
        ),
        migrations.AddField(
            model_name="transportserviceprovider",
            name="ticketing_system",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transport_service_providers",
                to="maas.ticketingsystem",
                verbose_name="ticketing system",
            ),
        ),
    ]
