# Generated by Django 3.1.7 on 2021-04-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maas", "0004_add_ticketing_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketingsystem",
            name="api_key",
            field=models.CharField(
                blank=True,
                help_text="API key that will be used for accessing the API",
                max_length=255,
                verbose_name="API key",
            ),
        ),
        migrations.AddField(
            model_name="ticketingsystem",
            name="api_url",
            field=models.URLField(
                default="http://localhost:8000/v1/mock_ticket/", verbose_name="API URL"
            ),
            preserve_default=False,
        ),
    ]
