# Generated by Django 3.1.7 on 2021-05-03 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maas", "0005_add_api_configuration_to_ticketing_system"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="permission",
            name="expires_at",
        ),
    ]
