# Generated by Django 3.2.2 on 2021-10-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maas", "0007_maasoperator_identifier"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticketingsystem",
            old_name="api_url",
            new_name="bookings_api_url",
        ),
        migrations.AlterField(
            model_name="ticketingsystem",
            name="bookings_api_url",
            field=models.URLField(verbose_name="API bookings endpoint URL"),
        ),
        migrations.AddField(
            model_name="ticketingsystem",
            name="availability_api_url",
            field=models.URLField(
                blank=True, verbose_name="API availability endpoint URL"
            ),
        ),
    ]
