# Generated by Django 3.1.7 on 2021-03-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gtfs", "0003_add_gtfs_model_api_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agency",
            name="api_id",
            field=models.UUIDField(unique=True, verbose_name="API ID"),
        ),
        migrations.AlterField(
            model_name="calendar",
            name="api_id",
            field=models.UUIDField(unique=True, verbose_name="API ID"),
        ),
        migrations.AlterField(
            model_name="fare",
            name="api_id",
            field=models.UUIDField(unique=True, verbose_name="API ID"),
        ),
        migrations.AlterField(
            model_name="route",
            name="api_id",
            field=models.UUIDField(unique=True, verbose_name="API ID"),
        ),
        migrations.AlterField(
            model_name="stop",
            name="api_id",
            field=models.UUIDField(unique=True, verbose_name="API ID"),
        ),
        migrations.AlterField(
            model_name="trip",
            name="api_id",
            field=models.UUIDField(unique=True, verbose_name="API ID"),
        ),
    ]
