# Generated by Django 3.1.7 on 2021-03-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gtfs", "0005_link_feed_to_ticketing_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="stoptime",
            name="stop_headsign",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="stop headsign"
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="direction_id",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="direction ID"
            ),
            preserve_default=False,
        ),
    ]
