# Generated by Django 3.1.7 on 2021-03-30 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gtfs", "0006_add_direction_id_and_stop_headsign"),
    ]

    operations = [
        migrations.CreateModel(
            name="Departure",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_id", models.UUIDField(unique=True, verbose_name="API ID")),
                ("date", models.DateField(verbose_name="date")),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departures",
                        to="gtfs.trip",
                        verbose_name="trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "departure",
                "verbose_name_plural": "departures",
                "default_related_name": "departures",
            },
        ),
        migrations.AddConstraint(
            model_name="departure",
            constraint=models.UniqueConstraint(
                fields=("trip", "date"), name="unique_trip_instance_date"
            ),
        ),
    ]
