# Generated by Django 3.1.7 on 2021-04-01 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gtfs", "0007_add_departure"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calendardate",
            name="calendar",
        ),
        migrations.RemoveField(
            model_name="calendardate",
            name="feed",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="calendar",
        ),
        migrations.DeleteModel(
            name="Calendar",
        ),
        migrations.DeleteModel(
            name="CalendarDate",
        ),
    ]
