# Generated by Django 3.1.7 on 2021-04-08 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gtfs", "0009_allow_empty_direction_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiderCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_id",
                    models.CharField(max_length=255, verbose_name="source ID"),
                ),
                ("api_id", models.UUIDField(unique=True, verbose_name="API ID")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="description"),
                ),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gtfs.feed",
                        verbose_name="feed",
                    ),
                ),
            ],
            options={
                "verbose_name": "rider category",
                "verbose_name_plural": "rider categories",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FareRiderCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="price"
                    ),
                ),
                (
                    "currency_type",
                    models.CharField(
                        help_text="ISO 4217 alphabetical currency code", max_length=3
                    ),
                ),
                (
                    "fare",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fare_rider_categories",
                        to="gtfs.fare",
                        verbose_name="fare",
                    ),
                ),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fare_rider_categories",
                        to="gtfs.feed",
                        verbose_name="feed",
                    ),
                ),
                (
                    "rider_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fare_rider_categories",
                        to="gtfs.ridercategory",
                        verbose_name="fare",
                    ),
                ),
            ],
            options={
                "verbose_name": "fare rider category",
                "verbose_name_plural": "fare rider categories",
                "default_related_name": "fare_rider_categories",
            },
        ),
        migrations.AddConstraint(
            model_name="ridercategory",
            constraint=models.UniqueConstraint(
                fields=("feed", "source_id"), name="unique_feed_gtfs_ridercategory"
            ),
        ),
        migrations.AddConstraint(
            model_name="fareridercategory",
            constraint=models.UniqueConstraint(
                fields=("fare", "rider_category"), name="unique_fare_rider_category"
            ),
        ),
    ]
