# Generated by Django 3.1.7 on 2021-04-13 20:07
from uuid import uuid5

from django.db import migrations, models

from gtfs.models.base import API_ID_NAMESPACE


def populate_api_id(apps, schema_editor):
    FareRiderCategory = apps.get_model("gtfs", "FareRiderCategory")
    for obj in FareRiderCategory.objects.all():
        obj.api_id = uuid5(
            API_ID_NAMESPACE,
            f"{FareRiderCategory.__class__.__name__}:{obj.feed_id}:{obj.fare.source_id}:{obj.rider_category.source_id}",
        )
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("gtfs", "0012_add_feed_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="fareridercategory",
            name="api_id",
            field=models.UUIDField(
                default="00000000-0000-0000-0000-000000000000", verbose_name="API ID"
            ),
            preserve_default=False,
        ),
        migrations.RunPython(populate_api_id, migrations.RunPython.noop),
    ]
