# Generated by Django 3.1.7 on 2021-04-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gtfs", "0013_add_fare_rider_category_api_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fareridercategory",
            name="api_id",
            field=models.UUIDField(unique=True, verbose_name="API ID"),
        ),
    ]
