# Generated by Django 3.1.7 on 2021-04-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gtfs", "0014_make_fare_rider_category_api_id_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="fare",
            name="description",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="fare",
            name="instructions",
            field=models.TextField(blank=True, verbose_name="instructions"),
        ),
        migrations.AddField(
            model_name="fare",
            name="name",
            field=models.CharField(blank=True, max_length=255, verbose_name="name"),
        ),
    ]
