# Generated by Django 3.1.7 on 2021-04-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gtfs", "0015_add_fare_extra_attributes"),
    ]

    operations = [
        migrations.AddField(
            model_name="fare",
            name="routes",
            field=models.ManyToManyField(
                blank=True,
                related_name="fares",
                through="gtfs.FareRule",
                to="gtfs.Route",
                verbose_name="routes",
            ),
        ),
        migrations.AddField(
            model_name="ridercategory",
            name="fares",
            field=models.ManyToManyField(
                blank=True,
                related_name="rider_categories",
                through="gtfs.FareRiderCategory",
                to="gtfs.Fare",
                verbose_name="fares",
            ),
        ),
    ]
