# Generated by Django 3.1.7 on 2021-04-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gtfs", "0017_remove_fareridercategory_api_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="fingerprint",
            field=models.CharField(
                blank=True,
                help_text="This value will be used to determine if the feed should be updated.",
                max_length=255,
                verbose_name="fingerprint",
            ),
        ),
    ]
