# Generated by Django 3.1.7 on 2021-04-20 11:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gtfs", "0018_add_fingerprint_to_feed"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shape",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_id",
                    models.CharField(max_length=255, verbose_name="source ID"),
                ),
                ("api_id", models.UUIDField(unique=True, verbose_name="API ID")),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.LineStringField(
                        srid=4326, verbose_name="geometry"
                    ),
                ),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shapes",
                        to="gtfs.feed",
                        verbose_name="feed",
                    ),
                ),
            ],
            options={
                "verbose_name": "shape",
                "verbose_name_plural": "shapes",
                "abstract": False,
                "default_related_name": "shapes",
            },
        ),
        migrations.AddField(
            model_name="trip",
            name="shape",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trips",
                to="gtfs.shape",
                verbose_name="shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="shape",
            constraint=models.UniqueConstraint(
                fields=("feed", "source_id"), name="unique_feed_gtfs_shape"
            ),
        ),
    ]
