# Generated by Django 3.1.7 on 2021-04-30 04:20

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ("gtfs", "0021_change_times_to_durations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agency",
            name="email",
        ),
        migrations.RemoveField(
            model_name="agency",
            name="fare_url",
        ),
        migrations.RemoveField(
            model_name="agency",
            name="name",
        ),
        migrations.RemoveField(
            model_name="agency",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="agency",
            name="url",
        ),
        migrations.RemoveField(
            model_name="route",
            name="desc",
        ),
        migrations.RemoveField(
            model_name="route",
            name="long_name",
        ),
        migrations.RemoveField(
            model_name="route",
            name="url",
        ),
        migrations.RemoveField(
            model_name="stop",
            name="desc",
        ),
        migrations.RemoveField(
            model_name="stop",
            name="name",
        ),
        migrations.RemoveField(
            model_name="stop",
            name="tts_name",
        ),
        migrations.RemoveField(
            model_name="stoptime",
            name="stop_headsign",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="headsign",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="short_name",
        ),
        migrations.CreateModel(
            name="TripTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                (
                    "headsign",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="headsign"
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="short name"
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="gtfs.trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "trip Translation",
                "db_table": "gtfs_trip_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name="StopTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=255, verbose_name="name"),
                ),
                ("desc", models.TextField(blank=True, verbose_name="description")),
                (
                    "tts_name",
                    models.CharField(
                        blank=True,
                        help_text="readable version of the name",
                        max_length=255,
                        verbose_name="TTS name",
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="gtfs.stop",
                    ),
                ),
            ],
            options={
                "verbose_name": "stop Translation",
                "db_table": "gtfs_stop_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name="StopTimeTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                (
                    "stop_headsign",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="stop headsign"
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="gtfs.stoptime",
                    ),
                ),
            ],
            options={
                "verbose_name": "stop times Translation",
                "db_table": "gtfs_stoptime_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name="RouteTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                (
                    "long_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="long name"
                    ),
                ),
                ("desc", models.TextField(blank=True, verbose_name="description")),
                ("url", models.URLField(blank=True, verbose_name="URL")),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="gtfs.route",
                    ),
                ),
            ],
            options={
                "verbose_name": "route Translation",
                "db_table": "gtfs_route_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name="AgencyTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="name")),
                ("url", models.URLField(verbose_name="URL")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=64, verbose_name="phone"),
                ),
                ("fare_url", models.URLField(blank=True, verbose_name="fare URL")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="gtfs.agency",
                    ),
                ),
            ],
            options={
                "verbose_name": "agency Translation",
                "db_table": "gtfs_agency_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
