# Generated by Django 3.1.7 on 2021-04-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gtfs", "0022_add_translations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feed",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="feed",
            name="import_attempted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="import attempted at"
            ),
        ),
        migrations.AddField(
            model_name="feed",
            name="imported_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="imported at"
            ),
        ),
        migrations.AddField(
            model_name="feed",
            name="last_import_error_message",
            field=models.TextField(blank=True, verbose_name="error message"),
        ),
        migrations.RenameField(
            model_name="feed",
            old_name="name",
            new_name="url_or_path",
        ),
        migrations.AlterField(
            model_name="feed",
            name="url_or_path",
            field=models.CharField(max_length=255, verbose_name="URL"),
        ),
        migrations.AddField(
            model_name="feed",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="If left empty, will be autopopulated with the feed info's publisher name when one is available.",
                max_length=255,
                verbose_name="name",
            ),
        ),
    ]
