# Generated by Django 3.1.7 on 2021-05-04 04:05

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ("gtfs", "0023_add_import_status_fields_to_feed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fare",
            name="description",
        ),
        migrations.RemoveField(
            model_name="fare",
            name="instructions",
        ),
        migrations.RemoveField(
            model_name="fare",
            name="name",
        ),
        migrations.RemoveField(
            model_name="ridercategory",
            name="description",
        ),
        migrations.RemoveField(
            model_name="ridercategory",
            name="name",
        ),
        migrations.CreateModel(
            name="RiderCategoryTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="description"),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="gtfs.ridercategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "rider category Translation",
                "db_table": "gtfs_ridercategory_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name="FareTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=255, verbose_name="name"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="description"
                    ),
                ),
                (
                    "instructions",
                    models.TextField(blank=True, verbose_name="instructions"),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="gtfs.fare",
                    ),
                ),
            ],
            options={
                "verbose_name": "fare Translation",
                "db_table": "gtfs_fare_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
