# Generated by Django 3.2.2 on 2021-08-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gtfs", "0024_translations_to_fare_and_rider_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="capacity_sales",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Disabled"),
                    (1, "Enabled"),
                    (2, "Required"),
                    (3, "Required for outbound"),
                    (4, "Required for inbound"),
                ],
                default=0,
                verbose_name="capacity sales",
            ),
        ),
    ]
