# Generated by Django 3.2.2 on 2021-10-22 13:03

from django.db import migrations, models
from django.db.models import F, Max


def populate_stop_times_stops_after_this(apps, schema_editor):
    Trip = apps.get_model("gtfs", "Trip")
    for trip in Trip.objects.all():
        max_stop_sequence = trip.stop_times.aggregate(
            max_stop_sequence=Max("stop_sequence")
        )["max_stop_sequence"]
        trip.stop_times.update(stops_after_this=max_stop_sequence - F("stop_sequence"))


class Migration(migrations.Migration):

    dependencies = [
        ("gtfs", "0025_add_more_capacity_sales_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="stoptime",
            name="stops_after_this",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="stops after this"
            ),
        ),
        migrations.RunPython(
            populate_stop_times_stops_after_this, reverse_code=migrations.RunPython.noop
        ),
    ]
