# Generated by Django 3.2.2 on 2021-10-22 13:03

from django.db import migrations, models


def populate_stop_times_stops_after_this(apps, schema_editor):
    Trip = apps.get_model("gtfs", "Trip")
    for trip in Trip.objects.all():
        trip.populate_stop_times_stops_after_this()


class Migration(migrations.Migration):

    dependencies = [
        ("gtfs", "0025_add_more_capacity_sales_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="stoptime",
            name="stops_after_this",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="stops after this"
            ),
        ),
        migrations.RunPython(
            populate_stop_times_stops_after_this, reverse_code=migrations.RunPython.noop
        ),
    ]
