# Generated by Django 3.1.7 on 2021-04-15 20:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("maas", "0004_add_ticketing_system"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "source_id",
                    models.CharField(max_length=255, verbose_name="source ID"),
                ),
                (
                    "api_id",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="API ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("RESERVED", "Reserved"), ("CONFIRMED", "Confirmed")],
                        default="RESERVED",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "maas_operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="maas.maasoperator",
                        verbose_name="MaaS operator",
                    ),
                ),
                (
                    "ticketing_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="maas.ticketingsystem",
                        verbose_name="ticketing system",
                    ),
                ),
            ],
            options={
                "verbose_name": "booking",
                "verbose_name_plural": "bookings",
                "default_related_name": "bookings",
            },
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                fields=("ticketing_system", "source_id"),
                name="unique_booking_source_id",
            ),
        ),
    ]
