# Generated by Django 3.1.7 on 2021-05-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="ticket_count",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="The amount of tickets that were requested from the ticketing system.",
                verbose_name="ticket count",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="transaction_id",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="transaction ID"
            ),
        ),
    ]
