# Generated by Django 3.1.7 on 2021-05-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="transaction_id",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="transaction ID"
            ),
        ),
    ]
